### add rating
post http://localhost:3000/institutes/addRating?institutId=653a4f6c4e6b26c828a4fccf
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDU2NjMyOCwiZXhwIjoxNzMwNDg2MzI4fQ.jkV4e8KWLZcHaZlZIHbT4LBM2LmMg3_fcB9QQUfu_gk; Path=/; HttpOnly; Secure; SameSite=None

{     "count":6
}

### updateRating
post http://localhost:3000/institutes/updateRating?institutId=653a4f6c4e6b26c828a4fccf
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDU2NjMyOCwiZXhwIjoxNzMwNDg2MzI4fQ.jkV4e8KWLZcHaZlZIHbT4LBM2LmMg3_fcB9QQUfu_gk; Path=/; HttpOnly; Secure; SameSite=None

{
    "count":78
}

### delet rating
delete http://localhost:3000/institutes/deleteRating?institutId=653a4f6c4e6b26c828a4fccf
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDU2NjMyOCwiZXhwIjoxNzMwNDg2MzI4fQ.jkV4e8KWLZcHaZlZIHbT4LBM2LmMg3_fcB9QQUfu_gk; Path=/; HttpOnly; Secure; SameSite=None

{
    
}

### get Institutes
get http://localhost:3000/institutes/getInstitutes/?limit=4
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwMzc1NDk2MiwiZXhwIjoxNzI5Njc0OTYyfQ.WLah5h4kDDAbm7xsBdMlO0VXU_j9JwCQhTMGuM71Mp8; Path=/; HttpOnly; Secure; SameSite=None

### get Institutes by id
get http://localhost:3000/institutes/getInstitutesById?id=653a4f6c4e6b26c828a4fcd1
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwMjAzODA1MCwiZXhwIjoxNzA0NjMwMDUwfQ.QVpOq5mlpw6WOVGiADcIwPtmMMNTchqKCMuVXujTtpE; Path=/; HttpOnly; Secure; SameSite=None
  
### search Institutes
get http://localhost:3000/institutes/search/?limit=4&search=טבריה
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDU4MTI1MCwiZXhwIjoxNzMwNTAxMjUwfQ.eBlcP50vJ80EDIM0lycFe_1o36o8Le56CujH1BLQnP8; Path=/; HttpOnly; Secure; SameSite=None

### get categories
get http://localhost:3000/institutes/categories
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTY5ODkxODA2NCwiZXhwIjoxNzAxNTEwMDY0fQ.3Sb1Ynz1P-1Lu2A2zww469Y0tMrM9nur1Y6vIi2Wk_k; Path=/; HttpOnly; Secure; SameSite=None

### get By categories
get http://localhost:3000/institutes/getByCategories?category=קורת גג&limit=4
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTY5ODkxODA2NCwiZXhwIjoxNzAxNTEwMDY0fQ.3Sb1Ynz1P-1Lu2A2zww469Y0tMrM9nur1Y6vIi2Wk_k; Path=/; HttpOnly; Secure; SameSite=None
