### add review
post http://localhost:3000/reviews/addReview?institutId=653a4f6c4e6b26c828a4fccf
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwMzk2NTc1OSwiZXhwIjoxNzI5ODg1NzU5fQ.PhbBQ6u8mO6guqTWyfCvww-rF_De7Ap3NNEEdAzQvGs; Path=/; HttpOnly; Secure; SameSite=None


{
  "Collaboration": {
    "comment": "אאאאאאאאאא",
    "rating": 1
  },
  "Maintenance": {
    "comment": "",
    "rating": 5
  },
  "ReligiousLevel": {
    "comment": "",
    "kind": "religious"
  },
  "AdjacentPsychiatrist": {
    "comment": "",
    "response": true
  },
  "HostFamilyOption": {
    "comment": "",
    "response": true
  },
  "StayOnSaturdaysAndHolidays": {
    "comment": "",
    "response": true
  },
  "isBoardingSchool": {
    "comment": "",
    "response": true
  },
  "emotionalResponse": {
    "comment": "",
    "response": false,
    "rating": 5
  },
  "afternoonClasses": {
    "comment": "",
    "response": true,
    "rating": 1
  }
}


### delet review
post http://localhost:3000/reviews/deleteReview?reviewId=6599c9b3e12ebbde610691f6
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDY2MjI1NCwiZXhwIjoxNzMwNTgyMjU0fQ.qLmkd-EFnwOZGKGYzyb53o8hc2xUQSl9xYII3y9vKp8; Path=/; HttpOnly; Secure; SameSite=None

### get review
get http://localhost:3000/reviews/getReviews/?institutId=653a4f6c4e6b26c828a4fccf&offset=4
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwMzc2MjU3OCwiZXhwIjoxNzI5NjgyNTc4fQ.fOZZ2iY4vLDgMOCmk0PnCsb9FME7KQtWXFBWrdeiCKA; Path=/; HttpOnly; Secure; SameSite=None

### get image
get http://localhost:3000/reviews/getImages/?institutId=653a4f6c4e6b26c828a4fccf
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNmNjBjMjBjYzQ5NzRkN2EyMTdhNTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMTcxOTIzMSwiZXhwIjoxNzM3NjM5MjMxfQ.iyCTQFrrFuj3daQXKoMXRi3em5BM-4FBxXk1ZpAtwCY; Path=/; HttpOnly; Secure; SameSite=None