get http://localhost:3000

### register
post http://localhost:3000/users/register
Content-Type: application/json

{
        "email":"pini554@gmail.com",
        "password":"123456",
        "name":"Pini"
}

### login
post http://localhost:3000/users/login
Content-Type: application/json

{
        "email":"pini554@gmail.com",
        "password":"123456"
}

